--increment for basic salary
DECLARE
    CURSOR C IS 
        SELECT EMPLOYEE_CATEGORY,BASIC
        FROM SALARY_INFO;
    V_BASIC SALARY_INFO.BASIC%TYPE;
    V_EMPLOYEE_CATEGORY SALARY_INFO.EMPLOYEE_CATEGORY%TYPE;
BEGIN
    OPEN C;
    LOOP
        FETCH C INTO V_BASIC,V_EMPLOYEE_CATEGORY;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_BASIC||' '||V_EMPLOYEE_CATEGORY);
    END LOOP;
    CLOSE C;
END;