

select * from LEAVE_INFO;
select * from SALARY_INFO;
select * from DEPART_INFO;
select * from EMPLOYEE_INFO;
select * from EMP_LEAVE_INFO;
select * from EMP_PAYROLL;


commit;

CREATE OR REPLACE PROCEDURE SALARY_DETAIL(EID EMPLOYEE_INFO.EMPID%TYPE)  
IS
  l_EMPLOYEE_ID EMPLOYEE_INFO.EMPID%TYPE;
  l_EMPLOYEE_NAME EMPLOYEE_INFO.EMPNAME%TYPE;
  L_DEPT_ID EMPLOYEE_INFO.DEPTID%TYPE;
  L_EMPLOYEE_CATEGORY employee_info.employee_category%TYPE;
  L_BASIC SALARY_INFO.BASIC%TYPE;
  
BEGIN
  SELECT
    EMPID,EMPNAME,DEPTID,A.employee_category,B.BASIC
  INTO
    l_EMPLOYEE_ID,l_EMPLOYEE_NAME, L_DEPT_ID, L_EMPLOYEE_CATEGORY,L_BASIC
  FROM
    EMPLOYEE_INFO A,SALARY_INFO B
  WHERE
    a.employee_category=b.employee_category AND EMPID =EID;
  DBMS_OUTPUT.PUT_LINE(l_EMPLOYEE_ID || ' : ' || l_EMPLOYEE_NAME||' '||L_DEPT_ID||' '|| L_EMPLOYEE_CATEGORY||' '||L_BASIC);
END;

EXEC SALARY_DETAIL('&EID');