select * from LEAVE_INFO;--2
select * from SALARY_INFO;----------------1
select * from DEPART_INFO;--2
select * from EMPLOYEE_INFO;--1
select * from EMP_LEAVE_INFO;--3 
select * from EMP_PAYROLL;-----------------2
------------------
---------LOSS OF PAY DUE TO LEAVE PROCEDUERE--------------

CREATE OR REPLACE PROCEDURE LOP(IN TOTAL_LEAVES)
IS
BEGIN
SELECT EMPID,TOTAL_LEAVES,LOPAMOUNT
FROM EMP_LEAVE_INFO,EMP_PAYROLL
WHERE TOTAL_LEAVES >5;

DBMS_OUTPUT.PUT_LINE('THE LOSS OF AMOUT IS : ' ||  (TOTAL_LEAVE-5*400));
EXCEPTION
WHEN OTHERS
DBMS_OUTPUT.PUT_LINE('THE ENTRY IS INVALID');
END;

